"""turning animal id necessary.

Revision ID: 5e9f3e735535
Revises: 1c1e0f5fb6f7
Create Date: 2025-07-07 07:51:38.358200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9f3e735535'
down_revision = '1c1e0f5fb6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco_prescricao', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bloco_prescricao', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
