"""adiciona animal_id ao bloco exames

Revision ID: 62f3bfc15a0b
Revises: 5e9f3e735535
Create Date: 2025-07-07 08:36:11.699036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f3bfc15a0b'
down_revision = '5e9f3e735535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco_exames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco_exames', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('animal_id')

    # ### end Alembic commands ###
