"""Tornar animal_id obrigatório em BlocoExames e remover consulta_id

Revision ID: 64f6db2f4af5
Revises: 62f3bfc15a0b
Create Date: 2025-07-07 08:46:13.003407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f6db2f4af5'
down_revision = '62f3bfc15a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco_exames', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('bloco_exames_consulta_id_fkey'), type_='foreignkey')
        batch_op.drop_column('consulta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco_exames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consulta_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('bloco_exames_consulta_id_fkey'), 'consulta', ['consulta_id'], ['id'])
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
