"""adding price and size of the package

Revision ID: 8646680f0507
Revises: 334510c0a96a
Create Date: 2025-07-01 09:20:37.757340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8646680f0507'
down_revision = '334510c0a96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_pago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tamanho_embalagem', sa.String(length=50), nullable=True))
        batch_op.drop_column('peso_animal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_animal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('tamanho_embalagem')
        batch_op.drop_column('preco_pago')

    # ### end Alembic commands ###
