"""fixing the backref

Revision ID: aec02838321c
Revises: 06494e44f482
Create Date: 2025-07-07 07:41:13.997101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec02838321c'
down_revision = '06494e44f482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco_prescricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('bloco_prescricao_consulta_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])
        batch_op.drop_column('consulta_id')

    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('prescricao_consulta_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])
        batch_op.drop_column('consulta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consulta_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prescricao_consulta_id_fkey'), 'consulta', ['consulta_id'], ['id'])
        batch_op.drop_column('animal_id')

    with op.batch_alter_table('bloco_prescricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consulta_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bloco_prescricao_consulta_id_fkey'), 'consulta', ['consulta_id'], ['id'])
        batch_op.drop_column('animal_id')

    # ### end Alembic commands ###
