const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const M = require('../static/js/sfa_entomologia_model.js');
const data = JSON.parse(fs.readFileSync(path.join(__dirname,'../services/data/entomologia/snapshot.json'),'utf8'));
const codes = new Set(data.census.features.map(f=>f.properties.sector));
const totals = M.aggregate(data.records);
assert.equal(totals.count, 2371);
assert.equal(totals.worked, 16507);
assert.equal(totals.positive, 215);
assert.equal(totals.informed, 422);
assert.equal(totals.missing, 1949);
assert.equal(totals.aegypti_larvae, 422);
assert.equal(M.filter(data.records,{mapping:'unmapped'},codes).length,43);
assert.equal(M.filter(data.records,{result:'positive'},codes).length,215);
assert.equal(M.filter(data.records,{result:'zero'},codes).length,207);
assert.equal(M.filter(data.records,{result:'missing'},codes).length,1949);
assert.equal(M.aggregate(M.filter(data.records,{result:'missing'},codes)).positive,null);
assert.equal(M.aggregate(M.filter(data.records,{result:'zero'},codes)).positive,0);
assert.equal(M.aggregate([]).coverage,null);
assert.equal(M.aggregate([]).positive,null);
assert.equal(M.sumKnown([{x:0},{x:null}], 'x'),0);
assert.equal(M.sumKnown([{x:null}], 'x'),null);
const jan=M.filter(data.records,{start:'2026-01-01',end:'2026-01-31'},codes);
assert.equal(M.aggregate(jan).positive,29);
const day=M.filter(data.records,{start:'2026-09-08',end:'2026-09-08'},codes);
assert.ok(day.length>0);
assert.ok(day.every(r=>r.date==='2026-09-08'));
const combo=M.filter(data.records,{sector:'353430205000001',species:'aegypti',result:'positive'},codes);
assert.ok(combo.every(r=>r.sector==='353430205000001'&&r.aegypti>0&&r.positive>0));
const series=M.timeline(jan,'2026-01-01','2026-03-31','positive');
assert.deepEqual(series.map(p=>p.value),[29,null,null]);
assert.deepEqual(M.timeline(jan,'2026-04-01','2026-03-31','positive'),[]);
const groups=M.grouped(data.records,'sector');
assert.equal([...groups.values()].reduce((s,a)=>s+(a.positive||0),0),215);
assert.equal([...groups.values()].reduce((s,a)=>s+a.count,0),2371);
assert.equal(M.density({population:0,area_km2:1}),0);
assert.equal(M.density({population:100,area_km2:0}),null);
assert.equal(M.density({population:null,area_km2:1}),null);
const csv=M.csv([{value:0},{value:null},{value:'=danger()'},{value:'a"b'}],[['value','Valor']]);
assert.equal(csv,'\ufeff"Valor"\r\n"0"\r\n""\r\n"\'=danger()"\r\n"a""b"');
console.log('Entomologia: totals, filters, missing values, reconciliation, timeline and CSV passed.');
const plan=M.planning(data.records,'2026-09-08',28);
assert.equal(plan.start,'2026-08-12');
assert.equal(plan.previousStart,'2026-07-15');
assert.equal(plan.previousEnd,'2026-08-11');
assert.equal(plan.current.count,238);
assert.equal(plan.previous.count,250);
assert.equal(plan.current.positive,14);
assert.equal(plan.current.closed,1161);
assert.equal(plan.current.refused,121);
assert.equal(plan.current.missing,170);
assert.equal(plan.previous.positive,15);
assert.equal(plan.groups.reduce((sum,r)=>sum+r.count,0),238);
assert.equal(M.workQueue(plan.groups,'focus')[0].sector,'353430205000017');
assert.equal(M.workQueue(plan.groups,'access')[1].sector,'353430205000045');
assert.equal(M.workQueue(plan.groups,'quality')[0].sector,'353430205000076');
assert.equal(M.shiftDate('2024-03-01',-1),'2024-02-29');
assert.throws(()=>M.shiftDate('2026-02-30',1));
assert.throws(()=>M.planning([],'2026-09-08',0));
const fixture=(date,sector,block,area,positive)=>({date,sector,block,area,...Object.fromEntries(M.metrics.map(k=>[k,null])),positive});
const edgeRows=[fixture('2026-02-22','1','1','A',1),fixture('2026-02-23','1','1','A',0),fixture('2026-03-01','1','1','A',1),fixture('2026-03-01','1','1','A',1),fixture('2026-03-01','2','1','A',null),fixture('2026-03-01','1','1','B',1),fixture('2026-03-02','1','1','A',5)];
const edge=M.planning(edgeRows,'2026-03-01',7);
assert.equal(edge.start,'2026-02-23');
assert.equal(edge.previous.positive,1);
assert.equal(edge.current.positive,3);
assert.equal(edge.groups[0].positive_days,1); // multiple rows on one date do not imply recurrence
assert.equal(edge.groups[1].positive,null);
const blocks=M.planning(edgeRows,'2026-03-01',7,'','block');
assert.equal(blocks.groups.length,3); // same block label in different sectors/areas remains separate
assert.equal(M.planning(edgeRows,'2026-03-01',7,'2').current.positive,null);
assert.deepEqual(M.workQueue(M.planning([],'2026-03-01',7).groups,'focus'),[]);
console.log('Planejamento: equal windows, boundaries, queue ordering, territory keys and missing data passed.');
