const assert=require('node:assert/strict');
const fs=require('node:fs');
const M=require('../static/js/sfa_condominios_model.js');
const F=require('../static/js/sfa_field_map_model.js');
const data=JSON.parse(fs.readFileSync('services/data/entomologia/atlas-referencias/condominios.json','utf8'));
const features=data.features.map(f=>({...f,atlasEntry:{id:f.properties.condominium,color:f.properties.color,origin:{type:'condominium'}}}));
assert.equal(features.length,394);
assert.equal(M.shortLabel(features[0]),'13');
assert.equal(M.number({...features[0],properties:{...features[0].properties,name:'Casa 250'}}),'250');
assert.equal(M.street(features[0]),'Alameda 02');
assert.deepEqual(M.overview(features).map(g=>[g.name,g.items.length]),[['Quebec',197],['Torino',197]]);
const center=[-47.8714,-20.708];
const project=c=>({x:(c[0]-center[0])*2e6+3500,y:(center[1]-c[1])*2e6+3500});
const candidates=M.candidates(features,project);
const placed=F.placeLabels(candidates,7000,7000,1);
assert.equal(placed.length,394,'Todos os números ficam legíveis com espaço suficiente no zoom próximo.');
placed.forEach((a,i)=>placed.slice(i+1).forEach(b=>assert.ok(Math.abs(a.x-b.x)>=(a.width+b.width)/2+2||Math.abs(a.y-b.y)>=22)));
const crowded=F.placeLabels(M.candidates(features,c=>({x:(c[0]-center[0])*2e5+350,y:(center[1]-c[1])*2e5+400})),700,900,1);
assert.ok(crowded.length>20&&crowded.length<394,'Zoom distante reduz números sem sobrepor os rótulos.');
assert.equal(M.streets(features,project).length,14);
assert.equal(M.isHouse({properties:{},atlasEntry:{origin:{type:'earth'}}}),false);
console.log('Condomínios: 394 casas, alamedas, edição do número e rótulos sem sobreposição verificados.');

const censusHouse={geometry:{type:'Point',coordinates:[-47.9,-20.7]},properties:{kind:'cnefe_house',house_number:'1963',name:'Rua 24, 1963'},atlasEntry:{origin:{type:'cnefe'}}};
assert.equal(M.isHouse(censusHouse),true);
assert.equal(M.shortLabel(censusHouse),'1963');
assert.equal(M.number({...censusHouse,properties:{...censusHouse.properties,house_number:'1963A',number_edited:true}}),'1963A');
assert.equal(M.isHouse({...censusHouse,properties:{kind:'cnefe_address',house_number:'1963',cnefe_building_type:'101',position_status:'unlocated'}}),false);
