"""orçamento

Revision ID: 045745abcdcf
Revises: 77414c8fd75c
Create Date: 2025-08-22 12:54:52.935110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045745abcdcf'
down_revision = '77414c8fd75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamento_item')
    # ### end Alembic commands ###
