"""remove legacy species breed text columns

Revision ID: 11319daa4cf1
Revises: 78f46e45e773
Create Date: 2026-04-15 16:02:08.909007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11319daa4cf1'
down_revision = '78f46e45e773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamento_plantonista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pendente','pago')", name='ck_pagamento_plantonista_status'),
    sa.CheckConstraint('valor_total >= 0', name='ck_pagamento_plantonista_valor_positive'),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['veterinario_id'], ['veterinario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamento_plantonista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamento_plantonista_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_plantonista_veterinario_id'), ['veterinario_id'], unique=False)

    op.create_table('cobertura_plantonista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('valor_hora', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valor_hora >= 0', name='ck_cobertura_plantonista_valor_hora_positive'),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamento_plantonista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cobertura_plantonista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobertura_plantonista_pagamento_id'), ['pagamento_id'], unique=False)

    with op.batch_alter_table('oauth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_token_access_token'))
        batch_op.drop_index(batch_op.f('ix_oauth_token_client_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_token_refresh_token'))

    op.drop_table('oauth_token')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('removido_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('falecido_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('animal_documento', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('bloco_exames', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('bloco_orcamento', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('bloco_prescricao', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('classified_transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('clinic_financial_snapshot', schema=None) as batch_op:
        batch_op.alter_column('gerado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('clinic_inventory_movement', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity_change',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity_before',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity_after',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_foreign_key(None, 'user', ['responsavel_id'], ['id'])

    with op.batch_alter_table('clinic_notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('resolution_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('clinic_taxes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.alter_column('fiscal_ready',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('authorization_checked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('finalizada_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('consulta_token', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('data_share_access', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('data_share_log', schema=None) as batch_op:
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('data_share_request', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('denied_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.alter_column('requested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('canceled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('exame_solicitado', schema=None) as batch_op:
        batch_op.alter_column('performed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('health_subscription', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('nfse_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfse_events_clinica_id'))
        batch_op.drop_index(batch_op.f('ix_nfse_events_nfse_issue_id'))

    with op.batch_alter_table('nfse_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfse_issues_clinica_id'))

    with op.batch_alter_table('nfse_xmls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfse_xmls_clinica_id'))
        batch_op.drop_index(batch_op.f('ix_nfse_xmls_nfse_issue_id'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('oauth_access_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_oauth_access_token_jti'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_oauth_access_token_value'), type_='unique')
        batch_op.create_index(batch_op.f('ix_oauth_access_token_access_token'), ['access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_access_token_jti'), ['jti'], unique=True)

    with op.batch_alter_table('oauth_authorization_code', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('oauth_authorization_code_code_key'), type_='unique')

    with op.batch_alter_table('oauth_client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('oauth_client_client_id_key'), type_='unique')

    with op.batch_alter_table('oauth_jwk_key', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_oauth_jwk_key_kid'), type_='unique')
        batch_op.create_index(batch_op.f('ix_oauth_jwk_key_grace_until'), ['grace_until'], unique=False)

    with op.batch_alter_table('oauth_refresh_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_oauth_refresh_token_jti'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_oauth_refresh_token_value'), type_='unique')
        batch_op.create_index(batch_op.f('ix_oauth_refresh_token_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_refresh_token_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_refresh_token_refresh_token'), ['refresh_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_refresh_token_replaced_by_jti'), ['replaced_by_jti'], unique=False)

    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('pj_payments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('plantao_modelos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('plantonista_escalas', schema=None) as batch_op:
        batch_op.alter_column('inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('fim',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('realizado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_plantonista_escalas_recurrence_group_id'))
        batch_op.drop_column('recurrence_group_id')
        batch_op.drop_column('recurrence_index')

    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.alter_column('data_prescricao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('racao', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('sfa_paciente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sfa_paciente_id_estudo_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('sfa_paciente_token_acesso_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_sfa_paciente_id_estudo'))
        batch_op.create_index(batch_op.f('ix_sfa_paciente_id_estudo'), ['id_estudo'], unique=True)
        batch_op.drop_index(batch_op.f('ix_sfa_paciente_token_acesso'))
        batch_op.create_index(batch_op.f('ix_sfa_paciente_token_acesso'), ['token_acesso'], unique=True)

    with op.batch_alter_table('sfa_sinan_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sfa_sinan_log_chave_dedup_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_sfa_sinan_log_chave_dedup'))
        batch_op.create_index(batch_op.f('ix_sfa_sinan_log_chave_dedup'), ['chave_dedup'], unique=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.alter_column('criada_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('vet_clinic_invite', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('veterinarian_membership', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('trial_ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('paid_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('veterinarian_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('veterinarian_membership', schema=None) as batch_op:
        batch_op.alter_column('paid_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('trial_ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('vet_clinic_invite', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.alter_column('criada_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('sfa_sinan_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sfa_sinan_log_chave_dedup'))
        batch_op.create_index(batch_op.f('ix_sfa_sinan_log_chave_dedup'), ['chave_dedup'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('sfa_sinan_log_chave_dedup_key'), ['chave_dedup'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('sfa_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sfa_paciente_token_acesso'))
        batch_op.create_index(batch_op.f('ix_sfa_paciente_token_acesso'), ['token_acesso'], unique=False)
        batch_op.drop_index(batch_op.f('ix_sfa_paciente_id_estudo'))
        batch_op.create_index(batch_op.f('ix_sfa_paciente_id_estudo'), ['id_estudo'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('sfa_paciente_token_acesso_key'), ['token_acesso'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('sfa_paciente_id_estudo_key'), ['id_estudo'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('racao', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.alter_column('data_prescricao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('plantonista_escalas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_index', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recurrence_group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_plantonista_escalas_recurrence_group_id'), ['recurrence_group_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('realizado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('fim',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('inicio',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('plantao_modelos', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('pj_payments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('paid_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('oauth_refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_token_replaced_by_jti'))
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_token_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_token_jti'))
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_token_family_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_oauth_refresh_token_value'), ['refresh_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_oauth_refresh_token_jti'), ['jti'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('oauth_jwk_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_jwk_key_grace_until'))
        batch_op.create_unique_constraint(batch_op.f('uq_oauth_jwk_key_kid'), ['kid'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('oauth_client', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('oauth_client_client_id_key'), ['client_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('oauth_authorization_code', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('oauth_authorization_code_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('oauth_access_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_access_token_jti'))
        batch_op.drop_index(batch_op.f('ix_oauth_access_token_access_token'))
        batch_op.create_unique_constraint(batch_op.f('uq_oauth_access_token_value'), ['access_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_oauth_access_token_jti'), ['jti'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('nfse_xmls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfse_xmls_nfse_issue_id'), ['nfse_issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfse_xmls_clinica_id'), ['clinica_id'], unique=False)

    with op.batch_alter_table('nfse_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfse_issues_clinica_id'), ['clinica_id'], unique=False)

    with op.batch_alter_table('nfse_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfse_events_nfse_issue_id'), ['nfse_issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfse_events_clinica_id'), ['clinica_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('health_subscription', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('exame_solicitado', schema=None) as batch_op:
        batch_op.alter_column('performed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.alter_column('canceled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('accepted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('requested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('data_share_request', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('denied_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('data_share_log', schema=None) as batch_op:
        batch_op.alter_column('occurred_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('data_share_access', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('consulta_token', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('finalizada_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('authorization_checked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('clinica', schema=None) as batch_op:
        batch_op.alter_column('fiscal_ready',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('clinic_taxes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('clinic_notifications', schema=None) as batch_op:
        batch_op.alter_column('resolution_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('clinic_inventory_movement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('quantity_after',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_before',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_change',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('clinic_financial_snapshot', schema=None) as batch_op:
        batch_op.alter_column('gerado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('classified_transactions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('bloco_prescricao', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('bloco_orcamento', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('bloco_exames', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('animal_documento', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('falecido_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('removido_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('date_added',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('oauth_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('oauth_token_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_token_pkey')),
    sa.UniqueConstraint('access_token', name=op.f('oauth_token_access_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('refresh_token', name=op.f('oauth_token_refresh_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('oauth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_token_refresh_token'), ['refresh_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_token_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_token_access_token'), ['access_token'], unique=True)

    with op.batch_alter_table('cobertura_plantonista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobertura_plantonista_pagamento_id'))

    op.drop_table('cobertura_plantonista')
    with op.batch_alter_table('pagamento_plantonista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamento_plantonista_veterinario_id'))
        batch_op.drop_index(batch_op.f('ix_pagamento_plantonista_clinica_id'))

    op.drop_table('pagamento_plantonista')
    # ### end Alembic commands ###
