"""add created_at to User

Revision ID: 334510c0a96a
Revises: 8778123677b6
Create Date: 2025-06-30 08:48:29.874096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334510c0a96a'
down_revision = '8778123677b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
