"""add pickup_location

Revision ID: 499352b63171
Revises: 84f46ec5c28e
Create Date: 2025-07-21 20:37:46.842707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499352b63171'
down_revision = '84f46ec5c28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pickup_location', ['pickup_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pickup_id')

    # ### end Alembic commands ###
