"""estoque e orçamento

Revision ID: 577a5ea273a3
Revises: ce451989ee23
Create Date: 2025-08-30 23:35:57.024632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a5ea273a3'
down_revision = 'ce451989ee23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloco_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamento_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloco_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bloco_orcamento', ['bloco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bloco_id')

    op.drop_table('bloco_orcamento')
    # ### end Alembic commands ###
