"""add amount field to payment

Revision ID: 621bcc65bd3e
Revises: b1d1be123abc
Create Date: 2025-07-23 12:12:49.653970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621bcc65bd3e'
down_revision = 'b1d1be123abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(10, 2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
