"""Initial migration

Revision ID: 6bb436fe2061
Revises: 
Create Date: 2025-12-19 15:01:25.796981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bb436fe2061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_share_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('denied_at', sa.DateTime(), nullable=True),
    sa.Column('denial_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('clinic_staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clinic_staff_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('data_share_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_share_access_animal_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_access_source_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_access_user_id'))

    with op.batch_alter_table('data_share_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_share_log_access_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_log_resource'))

    with op.batch_alter_table('health_claim', schema=None) as batch_op:
        batch_op.alter_column('request_format',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'json'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'received'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('health_coverage', schema=None) as batch_op:
        batch_op.alter_column('coverage_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=True,
               existing_server_default=sa.text("'procedimento'::character varying"))
        batch_op.alter_column('limit_period',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'lifetime'::character varying"))
        batch_op.alter_column('waiting_period_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('deductible_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('requires_authorization',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('health_coverage_usage', schema=None) as batch_op:
        batch_op.alter_column('amount_billed',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('amount_covered',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('health_plan_onboarding', schema=None) as batch_op:
        batch_op.alter_column('consent_signed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending_payment'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('orcamento_item', schema=None) as batch_op:
        batch_op.alter_column('coverage_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('pj_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pj_payments_data_servico'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pj_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pj_payments_data_servico'), ['data_servico'], unique=False)

    with op.batch_alter_table('orcamento_item', schema=None) as batch_op:
        batch_op.alter_column('coverage_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('health_plan_onboarding', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending_payment'::character varying"))
        batch_op.alter_column('consent_signed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('health_coverage_usage', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('amount_covered',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('amount_billed',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))

    with op.batch_alter_table('health_coverage', schema=None) as batch_op:
        batch_op.alter_column('requires_authorization',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('deductible_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('waiting_period_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('limit_period',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'lifetime'::character varying"))
        batch_op.alter_column('coverage_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=False,
               existing_server_default=sa.text("'procedimento'::character varying"))

    with op.batch_alter_table('health_claim', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'received'::character varying"))
        batch_op.alter_column('request_format',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'json'::character varying"))

    with op.batch_alter_table('data_share_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_share_log_resource'), ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_log_access_id'), ['access_id'], unique=False)

    with op.batch_alter_table('data_share_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_share_access_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_access_source_clinic_id'), ['source_clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_access_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('clinic_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clinic_staff_user_id_fkey'), 'user', ['user_id'], ['id'])

    op.drop_table('data_share_request')
    # ### end Alembic commands ###
