"""hey

Revision ID: 6ec5a8a3dea4
Revises: 3df4151ad641
Create Date: 2025-07-26 20:46:17.207994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec5a8a3dea4'
down_revision = '3df4151ad641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('animal_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('animal_added_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['added_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consulta_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('consulta_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consulta_token_tutor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tutor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('delivery_request_canceled_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('delivery_request_worker_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('delivery_request_requested_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['requested_by_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['canceled_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['worker_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('health_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('health_subscription_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interest_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_sender_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_receiver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_reviewed_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_reviewer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewed_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['reviewer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('saved_address', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('saved_address_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transaction_to_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('transaction_from_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['from_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['to_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_added_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['added_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('veterinarian_access', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('veterinarian_access_vet_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['vet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('veterinario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('veterinario_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('veterinario_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('veterinarian_access', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('veterinarian_access_vet_id_fkey'), 'user', ['vet_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_added_by_id_fkey'), 'user', ['added_by_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_from_user_id_fkey'), 'user', ['from_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('transaction_to_user_id_fkey'), 'user', ['to_user_id'], ['id'])

    with op.batch_alter_table('saved_address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_address_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_reviewer_id_fkey'), 'user', ['reviewer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('review_reviewed_user_id_fkey'), 'user', ['reviewed_user_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_receiver_id_fkey'), 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('message_sender_id_fkey'), 'user', ['sender_id'], ['id'])

    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('interest_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('health_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('health_subscription_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('delivery_request_requested_by_id_fkey'), 'user', ['requested_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('delivery_request_worker_id_fkey'), 'user', ['worker_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('delivery_request_canceled_by_id_fkey'), 'user', ['canceled_by_id'], ['id'])

    with op.batch_alter_table('consulta_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consulta_token_tutor_id_fkey'), 'user', ['tutor_id'], ['id'])

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consulta_created_by_fkey'), 'user', ['created_by'], ['id'])

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('animal_added_by_id_fkey'), 'user', ['added_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('animal_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
