"""reset migrations

Revision ID: 77414c8fd75c
Revises: 
Create Date: 2025-08-19 08:57:24.291412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77414c8fd75c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame_modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificativa', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame_modelo', schema=None) as batch_op:
        batch_op.drop_column('justificativa')

    # ### end Alembic commands ###
