"""add medicamento_favorito table

Revision ID: 7eb22b9c3ba9
Revises: d1a3f7c2b9e8
Create Date: 2026-05-04 19:35:16.157410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb22b9c3ba9'
down_revision = 'd1a3f7c2b9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamento_favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'medicamento_id', name='uq_fav_user_med')
    )
    with op.batch_alter_table('medicamento_favorito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicamento_favorito_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('accounting_accounts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_account_bank_transaction', 'bank_statement_transactions', ['bank_transaction_id'], ['id'], use_alter=True)

    with op.batch_alter_table('bank_statement_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'accounting_accounts', ['matched_account_id'], ['id'])

    with op.batch_alter_table('delivery_research_contact', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('delivery_research_contact_tutor_id_key'), type_='unique')

    with op.batch_alter_table('dose_medicamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dose_medicamento_especie_code'))
        batch_op.drop_index(batch_op.f('ix_dose_medicamento_medicamento_id'))

    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('classificacao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('principio_ativo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('via_administracao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('especies')
        batch_op.drop_column('indicacoes')
        batch_op.drop_column('interacoes')
        batch_op.drop_column('farmacologia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmacologia', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interacoes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('indicacoes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('especies', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('via_administracao',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('principio_ativo',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('classificacao',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('dose_medicamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dose_medicamento_medicamento_id'), ['medicamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_medicamento_especie_code'), ['especie_code'], unique=False)

    with op.batch_alter_table('delivery_research_contact', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('delivery_research_contact_tutor_id_key'), ['tutor_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('bank_statement_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('accounting_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_bank_transaction', type_='foreignkey')

    with op.batch_alter_table('medicamento_favorito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicamento_favorito_user_id'))

    op.drop_table('medicamento_favorito')
    # ### end Alembic commands ###
