"""add Species and Breed models

Revision ID: a0d491e443db
Revises: 64f6db2f4af5
Create Date: 2025-07-14 17:57:33.756154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d491e443db'
down_revision = '64f6db2f4af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('breed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'breed', ['breed_id'], ['id'])
        batch_op.create_foreign_key(None, 'species', ['species_id'], ['id'])
        batch_op.drop_column('species')
        batch_op.drop_column('breed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('breed_id')
        batch_op.drop_column('species_id')

    op.drop_table('breed')
    op.drop_table('species')
    # ### end Alembic commands ###
