"""add external_reference + unique constraints to payment

Revision ID: a89408e3a905
Revises: 499352b63171
Create Date: 2025-07-22 09:51:10.636838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89408e3a905'
down_revision = '499352b63171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_reference', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_payment_extref', ['external_reference'])
        batch_op.create_unique_constraint('uq_payment_tx', ['transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_tx', type_='unique')
        batch_op.drop_constraint('uq_payment_extref', type_='unique')
        batch_op.drop_column('external_reference')

    # ### end Alembic commands ###
