"""orçamento

Revision ID: cd4535f122b0
Revises: ee1a3963c0ed
Create Date: 2025-08-30 22:43:09.957147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4535f122b0'
down_revision = 'ee1a3963c0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamento_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orcamento_id', sa.Integer(), nullable=True))
        batch_op.alter_column('consulta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'orcamento', ['orcamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('consulta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('orcamento_id')

    op.drop_table('orcamento')
    # ### end Alembic commands ###
