"""rebuild migations

Revision ID: d94402dcb99e
Revises: 
Create Date: 2025-07-18 19:11:18.967981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94402dcb99e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('canceled_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['worker_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['canceled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('canceled_by_id')
        batch_op.drop_column('canceled_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('accepted_at')
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
