"""ração weight

Revision ID: dee1b546c208
Revises: 8646680f0507
Create Date: 2025-07-01 10:37:44.724153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee1b546c208'
down_revision = '8646680f0507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_racao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_pacote_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_racao', schema=None) as batch_op:
        batch_op.drop_column('peso_pacote_kg')

    # ### end Alembic commands ###
