"""pendingwebhook

Revision ID: e8aff173e0fe
Revises: a89408e3a905
Create Date: 2025-07-22 17:27:58.764357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8aff173e0fe'
down_revision = 'a89408e3a905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_webhook')
    # ### end Alembic commands ###
