"""add controle funcionarios

Revision ID: ee1a3963c0ed
Revises: 07d2ee21266f
Create Date: 2025-08-29 19:21:17.296494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1a3963c0ed'
down_revision = '07d2ee21266f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_manage_clients', sa.Boolean(), nullable=True),
    sa.Column('can_manage_animals', sa.Boolean(), nullable=True),
    sa.Column('can_manage_staff', sa.Boolean(), nullable=True),
    sa.Column('can_manage_schedule', sa.Boolean(), nullable=True),
    sa.Column('can_manage_inventory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_staff')
    # ### end Alembic commands ###
