"""vacina tutor

Revision ID: c1d9bdfe8bc2
Revises: 
Create Date: 2025-09-03 19:56:29.732525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d9bdfe8bc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aplicada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aplicada_em', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('aplicada_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['aplicada_por'], ['id'])
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('aplicada_por')
        batch_op.drop_column('aplicada_em')
        batch_op.drop_column('aplicada')

    # ### end Alembic commands ###
