"""recriação limpa

Revision ID: 3df4151ad641
Revises: 
Create Date: 2025-07-26 18:55:37.181729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df4151ad641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_address_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')

    with op.batch_alter_table('saved_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_address_user_id'))

    op.drop_table('saved_address')
    # ### end Alembic commands ###
