"""Pacote de modelos com reexportações para compatibilidade."""

from .base import *  # noqa: F401,F403
from .base import CasaDeRacao, CasaDeRacaoHorario  # noqa: F401
from .agenda import AgendaEvento, Appointment, ExamAppointment, PlantaoModelo, PlantonistaEscala, VetSchedule
from .loja import (
    DeliveryRequest,
    Order,
    OrderItem,
    Payment,
    PaymentMethod,
    PaymentStatus,
    PickupLocation,
    Product,
    ProductPhoto,
    SavedAddress,
    Transaction,
)
from .usuarios import (
    Endereco,
    Specialty,
    User,
    UserRole,
    Veterinario,
    VeterinarianMembership,
    VeterinarianSettings,
)
from .oauth import (
    OAuthAccessToken,
    OAuthAuthorizationCode,
    OAuthClient,
    OAuthConsent,
    OAuthJwkKey,
    OAuthRefreshToken,
    OAuthToken,
)
from .fiscal import (
    FiscalCertificate,
    FiscalCounter,
    FiscalDocument,
    FiscalDocumentStatus,
    FiscalDocumentType,
    FiscalEmitter,
    FiscalEvent,
)
from .sfa import (
    SfaAuditoria,
    SfaPaciente,
    SfaRespostaT0,
    SfaRespostaT10,
    SfaRespostaT30,
    SfaSinanLog,
)

__all__ = [
    "CasaDeRacao",
    "CasaDeRacaoHorario",
    "AgendaEvento",
    "Appointment",
    "AccountingAccount",
    "BankStatementTransaction",
    "ExamAppointment",
    "PlantonistaEscala",
    "PlantaoModelo",
    "VetSchedule",
    "PagamentoPlantonista",
    "CoberturaPlantonista",
    "DeliveryRequest",
    "DeliveryResearchContact",
    "Order",
    "OrderItem",
    "Payment",
    "PaymentMethod",
    "PaymentStatus",
    "PickupLocation",
    "Product",
    "ProductPhoto",
    "SavedAddress",
    "Transaction",
    "Endereco",
    "Specialty",
    "User",
    "UserRole",
    "Veterinario",
    "VeterinarianMembership",
    "VeterinarianSettings",
    "OAuthAccessToken",
    "OAuthAuthorizationCode",
    "OAuthClient",
    "OAuthConsent",
    "OAuthJwkKey",
    "OAuthRefreshToken",
    "OAuthToken",
    "FiscalCertificate",
    "FiscalCounter",
    "FiscalDocument",
    "FiscalDocumentStatus",
    "FiscalDocumentType",
    "FiscalEmitter",
    "FiscalEvent",
    "ClinicInventory",
    "ClinicInventoryMovement",
    "ProtocoloClinico",
    "ProtocoloClinicoExame",
    "ProtocoloClinicoMedicamento",
    "ProtocoloClinicoRetorno",
    "AuditoriaSugestaoClinica",
    "SfaAuditoria",
    "SfaPaciente",
    "SfaRespostaT0",
    "SfaRespostaT10",
    "SfaRespostaT30",
    "SfaSinanLog",
]
