"""Pacote de modelos com reexportações para compatibilidade."""

from .base import *  # noqa: F401,F403
from .base import CasaDeRacao, CasaDeRacaoHorario, CasaDeRacaoOnboardingInvite, StorePaymentAccount  # noqa: F401
from .agenda import AgendaEvento, Appointment, ExamAppointment, PlantaoModelo, PlantonistaEscala, VetSchedule
from .loja import (
    DeliveryRequest,
    Order,
    OrderItem,
    Payment,
    PaymentMethod,
    PaymentStatus,
    PickupLocation,
    Product,
    ProductPhoto,
    SavedAddress,
    Transaction,
)
from .usuarios import (
    Endereco,
    Specialty,
    User,
    UserRole,
    Veterinario,
    VeterinarianMembership,
    VeterinarianSettings,
)
from .oauth import (
    OAuthAccessToken,
    OAuthAuthorizationCode,
    OAuthClient,
    OAuthConsent,
    OAuthJwkKey,
    OAuthRefreshToken,
    OAuthToken,
)
from .fiscal import (
    FiscalCertificate,
    FiscalCounter,
    FiscalDocument,
    FiscalDocumentStatus,
    FiscalDocumentType,
    FiscalEmitter,
    FiscalEvent,
)
from .sfa import (
    SfaAuditoria,
    SfaPaciente,
    SfaRespostaT0,
    SfaRespostaT10,
    SfaRespostaT30,
    SfaSinanLog,
)
from .petsitter import (
    CareerApplication,
    PetsitterProfile,
    PetsitterRequest,
    ReferralCode,
    ReferralSignup,
)

__all__ = [
    "CasaDeRacao",
    "CasaDeRacaoHorario",
    "CasaDeRacaoOnboardingInvite",
    "StorePaymentAccount",
    "AgendaEvento",
    "Appointment",
    "AccountingAccount",
    "BankStatementTransaction",
    "ExamAppointment",
    "PlantonistaEscala",
    "PlantaoModelo",
    "VetSchedule",
    "PagamentoPlantonista",
    "CoberturaPlantonista",
    "PmoVaccinationAnimal",
    "PmoVaccinationVisit",
    "VaccineServiceItem",
    "VaccineServiceRequest",
    "VaccineServiceRequestItem",
    "VaccineServiceEvent",
    "DeliveryRequest",
    "DeliveryResearchContact",
    "Order",
    "OrderItem",
    "Payment",
    "PaymentMethod",
    "PaymentStatus",
    "PickupLocation",
    "Product",
    "ProductPhoto",
    "SavedAddress",
    "Transaction",
    "Endereco",
    "Specialty",
    "User",
    "UserRole",
    "Veterinario",
    "VeterinarianMembership",
    "VeterinarianSettings",
    "OAuthAccessToken",
    "OAuthAuthorizationCode",
    "OAuthClient",
    "OAuthConsent",
    "OAuthJwkKey",
    "OAuthRefreshToken",
    "OAuthToken",
    "FiscalCertificate",
    "FiscalCounter",
    "FiscalDocument",
    "FiscalDocumentStatus",
    "FiscalDocumentType",
    "FiscalEmitter",
    "FiscalEvent",
    "ExternalOnboardingInvite",
    "ExameImagem",
    "ExameImagemPdfAccessLog",
    "ClinicInventory",
    "ClinicInventoryMovement",
    "ProtocoloClinico",
    "ProtocoloClinicoExame",
    "ProtocoloClinicoMedicamento",
    "ProtocoloClinicoRetorno",
    "AuditoriaSugestaoClinica",
    "SfaAuditoria",
    "SfaPaciente",
    "SfaRespostaT0",
    "SfaRespostaT10",
    "SfaRespostaT30",
    "SfaSinanLog",
    "CareerApplication",
    "PetsitterProfile",
    "PetsitterRequest",
    "ReferralCode",
    "ReferralSignup",
]
