from flask import Blueprint

from blueprints.utils import lazy_view


def get_blueprint():
    bp = Blueprint("loja_routes", __name__)

    bp.add_url_rule(
        "/orders/new",
        view_func=lazy_view("create_order"),
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/orders/<int:order_id>/request_delivery",
        view_func=lazy_view("request_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/delivery_requests",
        view_func=lazy_view("list_delivery_requests"),
    )
    bp.add_url_rule(
        "/admin/delivery/<int:req_id>",
        view_func=lazy_view("admin_delivery_detail"),
    )
    bp.add_url_rule(
        "/worker/delivery/<int:req_id>",
        view_func=lazy_view("worker_delivery_detail"),
    )
    bp.add_url_rule(
        "/delivery_requests/<int:req_id>/accept",
        view_func=lazy_view("accept_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/delivery_requests/<int:req_id>/complete",
        view_func=lazy_view("complete_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/delivery_requests/<int:req_id>/cancel",
        view_func=lazy_view("cancel_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/delivery_requests/<int:req_id>/buyer_cancel",
        view_func=lazy_view("buyer_cancel_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/delivery/<int:req_id>",
        view_func=lazy_view("delivery_detail"),
    )
    bp.add_url_rule(
        "/admin/mapa_tutores",
        view_func=lazy_view("admin_tutor_map"),
    )
    bp.add_url_rule(
        "/admin/api/tutor_markers",
        view_func=lazy_view("admin_tutor_markers_api"),
    )
    bp.add_url_rule(
        "/admin/api/geocode_addresses",
        view_func=lazy_view("admin_geocode_addresses"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/admin/api/geocode_addresses/status",
        view_func=lazy_view("admin_geocode_status"),
    )
    bp.add_url_rule(
        "/admin/delivery_overview",
        view_func=lazy_view("delivery_overview"),
    )
    bp.add_url_rule(
        "/admin/delivery_requests/<int:req_id>/status/<status>",
        view_func=lazy_view("admin_set_delivery_status"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/admin/delivery_requests/<int:req_id>/delete",
        view_func=lazy_view("admin_delete_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/admin/delivery_requests/<int:req_id>/archive",
        view_func=lazy_view("admin_archive_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/admin/delivery_requests/<int:req_id>/unarchive",
        view_func=lazy_view("admin_unarchive_delivery"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/admin/delivery_archive",
        view_func=lazy_view("delivery_archive"),
    )
    bp.add_url_rule(
        "/admin/data-share-logs",
        view_func=lazy_view("admin_data_share_logs"),
    )
    bp.add_url_rule(
        "/delivery_archive",
        view_func=lazy_view("delivery_archive_user"),
    )
    bp.add_url_rule("/loja", view_func=lazy_view("loja"))
    bp.add_url_rule("/loja/data", view_func=lazy_view("loja_data"))
    bp.add_url_rule(
        "/produto/<int:product_id>",
        view_func=lazy_view("produto_detail"),
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/carrinho/adicionar/<int:product_id>",
        view_func=lazy_view("adicionar_carrinho"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/carrinho/increase/<int:item_id>",
        view_func=lazy_view("aumentar_item_carrinho"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/carrinho/decrease/<int:item_id>",
        view_func=lazy_view("diminuir_item_carrinho"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/carrinho",
        view_func=lazy_view("ver_carrinho"),
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/carrinho/salvar_endereco",
        view_func=lazy_view("carrinho_salvar_endereco"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/checkout/confirm",
        view_func=lazy_view("checkout_confirm"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/checkout",
        view_func=lazy_view("checkout"),
        methods=["POST"],
    )
    bp.add_url_rule(
        "/notificacoes",
        view_func=lazy_view("notificacoes_mercado_pago"),
        methods=["POST", "GET"],
    )
    bp.add_url_rule(
        "/pagamento/<status>",
        view_func=lazy_view("legacy_pagamento"),
    )
    bp.add_url_rule(
        "/order/<int:order_id>/edit_address",
        view_func=lazy_view("edit_order_address"),
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/payment_status/<int:payment_id>",
        view_func=lazy_view("payment_status"),
    )
    bp.add_url_rule(
        "/minhas-compras",
        view_func=lazy_view("minhas_compras"),
    )
    bp.add_url_rule(
        "/pedido/<int:order_id>",
        view_func=lazy_view("pedido_detail"),
    )
    return bp
